		c1 = request.form['agreement_number']
		c2 = request.form['urn']
		c3 = request.form['sales_code']
		c3a = request.form['salesperson']
		c4 = request.form['customer_category']
		c5 = request.form['business_name']
		c5 = request.form['business_fullname']

		c6 = request.form['business_addressline1']
		c7 = request.form['business_addressline2']
		c8 = request.form['business_town']
		c9 = request.form['business_county']
		c10 = request.form['business_postcode']


		c11 = request.form['business_previousname1']
		c12 = request.form['business_previousname2']
		c13 = request.form['business_telnumber']
		c14 = request.form['business_faxnumber']
		c15 = request.form['business_coreg']
		c16 = request.form['business_vat']
		c17 = request.form['number_of_employees']
		c18 = request.form['contact_prefix']

		c19 = request.form['contact_firstname']
		c20 = request.form['contact_initial']
		c21 = request.form['cpmtact_lastname']
		c22 = request.form['contact_telnumber']
		c23 = request.form['contact_title']
		c24 = request.form['contact_email']
		c25 = request.form['contact_daynumber']
		c26 = request.form['contact_department']


		c27 = request.form['director_prefix']
		c28 = request.form['director_firstname']
		c29 = request.form['director_initial']
		c30 = request.form['director_lastname']
		c31 = request.form['director_dob']
		c34 = request.form['director_addressline1']
		c35 = request.form['director_addressline2']
		c36 = request.form['director_town']
		c37 = request.form['director_county']
		c38 = request.form['director_postcode']

		c39 = request.form['director_status']
		c40 = request.form['director_addresslot']
		# if less than three years, 
		c40a = request.form['director_previousline1']
		c40b = request.form['director_previousline2']
		c40c = request.form['director_previoustown']
		c40d = request.form['director_previouscounty']
		c40e = request.form['director_previouspostcode']
		c41 = request.form['director_telnumber']
		c42 = request.form['director_daynumber']
		c43 = request.form['director_email']
		c44 = request.form['director_banklot']
		c45 = request.form['director_status']
		c46 = request.form['director_creditcard']
		c47 = request.form['director_joblot']